server:
  port: 8001
spring:
  application:
    name: cloud-payment-provider8001
  datasource:
    #当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #mysql驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 5201314

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.yan.cloud.entity


eureka:
  instance:
    hostname: cloud-provider-payment8001
    instance-id: payment8001

  client:
    register-with-eureka: true #向eureka服务中心注册自己
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/