CREATE DATABASE cloud;
USE CLOUD;

CREATE TABLE `cloud`.`PAYMENT`  (
  `ID` int(20) NOT NULL AUTO_INCREMENT,
  `SERIAL` varchar(255) NULL,
  PRIMARY KEY (`ID`)
)ENGINE = InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8